# Generated by Django 3.0.8 on 2020-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
