# Generated by Django 3.0.8 on 2020-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntech', '0002_user_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseData',
            field=models.TextField(default='Error'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseVideo',
            field=models.TextField(blank=True),
        ),
    ]
