# Generated by Django 3.0.8 on 2020-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntech', '0003_auto_20200910_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursePrice',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseData',
            field=models.TextField(),
        ),
    ]
