# Generated by Django 3.0.8 on 2020-09-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learntech', '0004_auto_20200917_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageData', models.TextField()),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageReceiver', to=settings.AUTH_USER_MODEL)),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
